#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(font_inter_regular_12)
LV_FONT_DECLARE(font_inter_regular_14)
LV_FONT_DECLARE(font_inter_semibold_14)
LV_FONT_DECLARE(font_inter_bold_16)
LV_FONT_DECLARE(font_inter_bold_18)
LV_FONT_DECLARE(font_inter_display_bold_108)
LV_FONT_DECLARE(font_jetbrainsmono_medium_12)
LV_FONT_DECLARE(font_symbols_12)
LV_FONT_DECLARE(font_symbols_14)